name:       thinkorswim
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

dependencies:
  - base
  - aeson
  - aeson-schema
  - bytestring
  - containers
  - lens
  - pretty-show
  - servant
  - servant-client
  - text
  - time
  - uri-encode

library:
  source-dirs: src
  exposed-modules:
    - Data.Ledger
    - ThinkOrSwim.API
    - ThinkOrSwim.API.TransactionHistory.GetTransactions
    - ThinkOrSwim.Convert
    - ThinkOrSwim.Gains
  dependencies:
    - megaparsec
    - reflection
    - tagged
    - vector
    - mtl
    - rounded
    - tasty
    - tasty-hunit

executables:
  thinkorswim:
    main: Main.hs
    dependencies:
      - thinkorswim
      - http-client
      - http-client-tls
      - optparse-applicative
