name:       thinkorswim
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

ghc-options:
  - -Wall
  # - -Werror
  - -debug
  - -g3
  - -fno-ignore-asserts

dependencies:
  - base
  - aeson
  - bytestring
  - containers
  - data-default
  - lens
  - mtl
  - optparse-applicative
  - pretty
  - pretty-show
  - profunctors
  - servant
  - servant-client
  - split
  - text
  - time
  - transformers
  - uri-encode
  - vector

library:
  source-dirs: src
  c-sources:
    - src/Data/mpfr_printf.c
  extra-libraries:
    - mpfr
    - gmp
  exposed-modules:
    - Data.Amount
    - Data.Ledger
    - Data.Ledger.Render
    - Data.Split
    - Data.Utils
    - ThinkOrSwim.API
    - ThinkOrSwim.API.TransactionHistory.GetTransactions
    - ThinkOrSwim.Convert
    - ThinkOrSwim.Event
    - ThinkOrSwim.Options
    - ThinkOrSwim.Types

tests:
  thinkorswim-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - thinkorswim
      - HUnit
      - hedgehog
      - mmorph
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - transformers

executables:
  thinkorswim:
    main: Main.hs
    dependencies:
      - thinkorswim
      - http-client
      - http-client-tls
