name:       thinkorswim
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

dependencies:
  - base
  - text
  - bytestring
  - aeson
  - aeson-schema
  - servant
  - servant-client
  - time

library:
  source-dirs: src
  exposed-modules:
    - ThinkOrSwim.API
    - ThinkOrSwim.API.TransactionHistory.GetTransactions

executables:
  thinkorswim:
    main: Main.hs
    dependencies:
      - thinkorswim
      - http-client
