name:       thinkorswim
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

dependencies:
  - base
  - text
  - bytestring
  - aeson
  - aeson-schema
  - servant
  - servant-client
  - time
  - uri-encode

library:
  source-dirs: src
  exposed-modules:
    - ThinkOrSwim.API
    - ThinkOrSwim.API.TransactionHistory.GetTransactions
  dependencies:
    - lens
    - megaparsec

executables:
  thinkorswim:
    main: Main.hs
    dependencies:
      - thinkorswim
      - http-client
      - http-client-tls
      - pretty-show
