name:       thinkorswim
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

dependencies:
  - base
  - aeson
  - aeson-schema
  - bytestring
  - containers
  - lens
  - mtl
  - pretty-show
  - profunctors
  - servant
  - servant-client
  - split
  - text
  - time
  - uri-encode
  - vector

library:
  source-dirs: src
  c-sources:
    - src/Data/mpfr_printf.c
  extra-libraries:
    - mpfr
    - gmp
  exposed-modules:
    - Data.Amount
    - Data.Ledger
    - ThinkOrSwim.API
    - ThinkOrSwim.API.TransactionHistory.GetTransactions
    - ThinkOrSwim.Convert
    - ThinkOrSwim.Gains

tests:
  thinkorswim-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - thinkorswim
      - hedgehog
      - tasty
      - tasty-hunit
      - tasty-hedgehog

executables:
  thinkorswim:
    main: Main.hs
    dependencies:
      - thinkorswim
      - http-client
      - http-client-tls
      - optparse-applicative
